### ISSUE TITLE
Any comparison about different models?

### ISSUE THREAD

**Issue by liruilong940607** [git-hcLee/carnava-image-masking-challenge#1]
You have implemented many great segmentation networks.

Have you got any comparison about different models on performance ?

For example, UNet V.S. DeepLabv2 V.S. DeepLabv3(which I interest most) ...

Looking forward to your responds

**Comment by git-hcLee** [comment]
hi. Yes, I did. For this task, DeepLabv3 performed badly ~92% IOU. I guess maybe it's because the final conv output is resized X8 directly. So the model I used in the final submission was a modified UNet  with dilate conv  and inception block (you can see GoogleNet). : )
